# Usa una imagen oficial de Python como base
FROM python:3.11-slim

# Establece el directorio de trabajo
WORKDIR /app

# Copia los archivos estáticos al contenedor
COPY index.html /app/
COPY css/ /app/css
COPY js/ /app/js
COPY img/ /app/js
# Exponer el puerto 8000 para el servidor Web
EXPOSE 8000

# Comando para iniciar el servidor web
CMD ["python3", "-m", "http.server", "8000"]
